version: "3.9"

services:

  reverseproxy:
    build:
      context: ./nginx
    container_name: nginxrp
    volumes:
      - ./nginx/html:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "1880:80"
    command: nginx -g  "daemon off;"
