version: "3.9"

services:

  reverseproxy:
    build:
      context: ./nginx
    container_name: nginxrp
    volumes:
      - ./public_html:/public_html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./dhparam:/etc/nginx/dhparam
      - ./certbot/conf:/etc/nginx/ssl
      - ./certbot/data:/usr/share/nginx/html/letsencrypt
    ports:
      - 1880:80
      - 443:443
    command: nginx -g  "daemon off;"


  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email younes_zerouali@hotmail.com --agree-tos --no-eff-email -d carsnatch.au -d www.carsnatch.ai
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/logs:/var/log/letsencrypt
      - ./certbot/data:/usr/share/nginx/html/letsencrypt


  carsapp:
    build:
      context: ./mlcars
    container_name: carsapp_server
    ports:
      - "5001:5000"
    #command: docker build -t mlcarsapp --build-arg SSH_KEY="$$(cat ~/.ssh/id_rsa_mlcdeploy)" mlcars/.
